### ISSUE TITLE
Optimizations when Environment.ProcessorCount > 1 in Kubernetes environment

### ISSUE THREAD

**Issue by tylerohlsen** [dotnet/coreclr#20222]
I've noticed that our pods on a Kubernetes/Docker cluster with millicpu allocations all report Environment.ProcessorCount = 1.  

Does the .Net Core CLR have any optimizations when Environment.ProcessorCount > 1 that we are missing out on or is anything is disabled or degraded when Environment.ProcessorCount = 1?

**Comment by benaadams** [comment]
Threadpool min thread count and GC heaps (in server mode) are based on processor count. This may be desirable for GC as it will also use less memory (depending if the pod with a millicpu allocation also has lower assigned memory).

Threadpool min levels can increased with [`ThreadPool.SetMinThreads(Int32, Int32)`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.setminthreads?view=netcore-2.1) if the processor count defaults aren't working for you.

Other aspect I'm aware of is some concurrent datastructures/locks won't do optimistic spins if there is only one processor; but move straight to yielding/sleeping when blocked.

**Comment by tylerohlsen** [comment]
FYI to anyone that stumbles across this.  Environment.ProcessorCount will equal the integer upper limit of resources you give a pod.

So this spec will report Environment.ProcessorCount = 4
```yaml
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "4000m"
```

And this spec will report Environment.ProcessorCount = 2
```yaml
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "2500m"
```
